### PR TITLE
Back to downloading of jars

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Closes: #41 

This PR essentially reverts #25. Differences:
- use `ureq` instead `reqwest` as `ureq` is more lightweight
- download jars from our repository instead of downloading them from the releases page of their repositories; this prevents situations where a GitHub release is deleted, which would result in `modelator` not working
- ensure that jars were not corrupted by embedding their SHA256 hash in the Rust code and checking that hashes match after the jars are written to disk

### CODE REVIEW

**Comment by andrey-kuprianov** [comment]
Nice Vitor! I think it is really good that way -- I like the minimal dependency introduced, as well that it's now downloaded from our repo.

Feel free to merge:)

**Comment by andrey-kuprianov** [comment]
Just an afterthought: I think it would be nice when the JARs are downloaded to display to the user the information like

```
Downloading model-checkers:
  downloading Apalache ... done
  downloading TLC ... done
```

This way the user will understand where the initial delay comes from.

**Comment by romac** [comment]
I would also embed the SHA-256 hashes of each JAR file and check them after having downloaded them, to ensure they were not corrupted or tempered with during transfer.

**Comment by andrey-kuprianov** [comment]
> May I suggest embedding the SHA-256 hashes of each JAR file in the Rust code, and checking them after the download to ensure they were not corrupted or tempered with during transfer.

that is a very good idea!

**Comment by vitorenesduarte** [comment]
> May I suggest embedding the SHA-256 hashes of each JAR file in the Rust code, and checking them after the download to ensure they were not corrupted or tempered with during transfer.

`ureq` uses TLS by default: https://github.com/algesten/ureq/blob/main/Cargo.toml#L18
Doesn't this prevent that situation?

**Comment by romac** [comment]
> Doesn't this prevent that situation?

It does prevent against tampering during transfer but not corruption, nor can it do anything about file system bugs or bitflips, etc. so I would still advise checking the hash to ensure the file that's been downloaded and written to disk is intact.

**Comment by vitorenesduarte** [comment]
> > Doesn't this prevent that situation?
> 
> It does prevent against tampering during transfer but not corruption when writing to disk for example. I would therefore still advise checking the hash to ensure the file that's been downloaded and written to disk is intact.

That makes sense, thanks! Done in 4b2720812b9abb75a8ea1754f316375b1879ef38. I'll update the top-level comment accordingly.

**Comment by vitorenesduarte** [comment]
> Just an afterthought: I think it would be nice when the JARs are downloaded to display to the user the information like
> 
> ```
> Downloading model-checkers:
>   downloading Apalache ... done
>   downloading TLC ... done
> ```
> 
> This way the user will understand where the initial delay comes from.

Done in 75624612ac4159dc880157bdcb486db327608c61.

**Pull request merged**
