### PR TITLE
Run CI on Windows and MacOS

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by andrey-kuprianov** [comment]
Hi @vitorenesduarte ! what's with this PR? is it supposed to be merged, or is it still a draft? the checks are failing...

**Comment by danwt** [comment]
It seems that only Windows is failing right now, so we could benefit from having Mac CI by only removing the Windows related parts.

**Comment by andrey-kuprianov** [comment]
@danwt that sounds like a good idea!

**Comment by rnbguy** [comment]
@danwt the `ubuntu-latest` is failing because of `tmate`. It requires you to have an SSH key at your Github profile.

tmate docs: https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys

**Comment by rnbguy** [comment]
Ignoring the empty conflict, this PR is ready to be merged on `main`.

**Comment by rnbguy** [comment]
Done - with Windows! These two calls needed to be swapped. Windows is very strict about these.
https://github.com/informalsystems/modelator/blob/32706f1196d227a1af8b99823c2e111f0928fb71/modelator/src/lib.rs#L121-L124

**Pull request merged**
