### PR TITLE
Use Apalache 0.25.10 by default

### PR DESCRIPTION
**Pull request by hvanz**
Closes: #224

### CODE REVIEW

**Review by ivan-gavran — CHANGES_REQUESTED** [review]
Overall, this looks very good to me. 
There is only one thing that I'd like to discuss: now that you decided to have the version in the Apalache filename, the older versions will remain on the disk whenever we upgrade. Is there any benefit in keeping older versions around?

If not (which seems to be the case), then we should remove any old versions before downloading a new one.

**Comment by rnbguy** [comment]
Usually the apps keep old data. They provide something like `atomkraft data clear` to wipe it necessary.

**Review by andrey-kuprianov — APPROVED** [review]
LGTM:)

I suggest we merge to unblock subsequent PRs

**Review by ivan-gavran — APPROVED** [review]

**Comment by hvanz** [comment]
> If not (which seems to be the case), then we should remove any old versions before downloading a new one.
 For the moment I will keep the older versions. This has the advantage for us of quickly changing versions if we want to test something, without downloading. I will add to the CLI a command to clean the data, as Rano suggested.

**Pull request merged**
