### PR TITLE
modelator tutorial

### LINKED ISSUE #287: modelator User Manual
Hello, I have been using TLA+ before, and I found that modelator is a good test method, but when I started to use modelator, I found that I could not find the relevant manual for modelator. Excuse me, is there a manual for modelator in the community? for me to learn and use

### PR DESCRIPTION
**Pull request by rnbguy**
Closes #287 

Tutorial to generate ITF traces and use `modelator` as `pytest` library to perform model-based testing. 

[Link](https://github.com/informalsystems/modelator/tree/rano/tutorial/examples/hanoi) to directory.

### CODE REVIEW

**Comment by ivan-gavran** [comment]
@rnbguy, shall we merge this PR? Even if it is not complete/detailed, it would still be useful to have a ready-to-look at example, and then improve it later.

**Comment by rnbguy** [comment]
Yea go ahead 🙂 we can polish this later.

**Review by ivan-gavran — APPROVED** [review]
I added two commits to update to new Apalache type system. I also had to modify the reactor ([2nd commit](https://github.com/informalsystems/modelator/pull/290/commits/aac3a4db0474519d4715f3ac8b0ad54c0bef2302)) to not read number of discs from the trace.
This might be a questionable decision, but I did so to avoid adding a variant to the action type (it makes the whole example much less readable, which is the prime purpose of an example).

Please, go ahead an merge the PR @rnbguy  (leaving it to you in case you have objections to my changes)

**Comment by rnbguy** [comment]
Thanks for updating the example to TS1.2 @ivan-gavran :+1:

**Pull request merged**
