### PR TITLE
Markdown ITF traces

### LINKED ISSUE #266: Easy-to-understand trace representation
As requested by @tesnimab, as a feature likely to be much needed by our users, alongside with the [ITF trace](https://apalache.informal.systems/docs/adr/015adr-trace.html) representation (for automatic processing), we need to produce an easy-to-understand representation for humans.

For that we can use the (tweaked) version of the tabular differential representation that has been developed by @rnbguy. This could be implemented e.g. as follows:

When we call `atomkraft model sample --examples "Ex1,Ex2"` then a trace `trace1` is produced for `Ex1` by an Atomkraft command, it is stored in the following forms:
- `traces/<timestamp>/Ex1/trace1.itf.json` (for automatic processing)
- `traces/<timestamp>/Ex1/trace1.txt` (complete tabular representation, with all state components)
- `traces/<timestamp>/Ex1/trace1.diff.txt` (shortened tabular representation, with only differences between consecutive states)

Other alternatives are of course possible, and should be discussed.

This feature is fine to implement in the feature freeze period, before the prototype release, because:
 - it is requested by our product owner as critical, and
 - it concerns only with output, so no unforeseen interactions with other components should happen.

### LINKED ISSUE #267: Add mdx tests to CI workflow

### PR DESCRIPTION
**Pull request by rnbguy**
Closes #266 
Closes #267 

## Description

`_run_checker` will now produce human-readable traces (`.itf.md`, `.itf.diff.md`) in markdown form along with `.itf.json`.

Next two comments are example outputs for `.itf.md`, `.itf.diff.md`.

______

For contributor use:

- [ ] If applicable, unit tests are written and added to CI.
- [ ] Ran `go fmt`, `cargo fmt` and etc. (or had formatting run automatically on all files edited)
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).

### CODE REVIEW

**Comment by rnbguy** [comment]
# ITF Markdown

## Step 1

<details open>

<summary>Variables</summary>


|KeyPath|Value|
|-|-|
|`.action`|`[ tag \|-> "Init", value \|-> [ n_wallet \|-> 2 ] ]`|
|`.balances`|`SetAsFun({<<0, 100>>, <<1, 100>>})`|
|`.step`|`0`|


</details>

## Step 2

<details open>

<summary>Variables</summary>


|KeyPath|Value|
|-|-|
|`.action`|`[ tag \|-> "Transfer", value \|-> [ amount \|-> 1, receiver \|-> 0, sender \|-> 1 ] ]`|
|`.balances`|`SetAsFun({<<0, 101>>, <<1, 99>>})`|
|`.step`|`1`|


</details>

## Step 3

<details open>

<summary>Variables</summary>


|KeyPath|Value|
|-|-|
|`.action`|`[ tag \|-> "Transfer", value \|-> [ amount \|-> 1, receiver \|-> 0, sender \|-> 1 ] ]`|
|`.balances`|`SetAsFun({<<0, 102>>, <<1, 98>>})`|
|`.step`|`2`|


</details>

## Step 4

<details open>

<summary>Variables</summary>


|KeyPath|Value|
|-|-|
|`.action`|`[ tag \|-> "Transfer", value \|-> [ amount \|-> 1, receiver \|-> 0, sender \|-> 1 ] ]`|
|`.balances`|`SetAsFun({<<0, 103>>, <<1, 97>>})`|
|`.step`|`3`|


</details>

## Step 5

<details open>

<summary>Variables</summary>


|KeyPath|Value|
|-|-|
|`.action`|`[ tag \|-> "Transfer", value \|-> [ amount \|-> 97, receiver \|-> 0, sender \|-> 1 ] ]`|
|`.balances`|`SetAsFun({<<0, 200>>, <<1, 0>>})`|
|`.step`|`4`|


</details>

**Comment by rnbguy** [comment]
# ITF-Diff Markdown

## Step 1 to Step 2

<details open>

<summary>Variables</summary>

<details open>

<summary>.action</summary>


|KeyPath|Old|New|
|-|-|-|
|`.action.tag`|`Init`|`Transfer`|
|`.action.value.amount`|`None`|`1`|
|`.action.value.receiver`|`None`|`0`|
|`.action.value.sender`|`None`|`1`|
|`.action.value.n_wallet`|`2`|`None`|

</details>
<details open>

<summary>.balances</summary>


|KeyPath|Old|New|
|-|-|-|
|`.balances(0)`|`100`|`101`|
|`.balances(1)`|`100`|`99`|

</details>
<details open>

<summary>.step</summary>


|KeyPath|Old|New|
|-|-|-|
|`.step`|`0`|`1`|

</details>

</details>

## Step 2 to Step 3

<details open>

<summary>Variables</summary>

<details open>

<summary>.balances</summary>


|KeyPath|Old|New|
|-|-|-|
|`.balances(0)`|`101`|`102`|
|`.balances(1)`|`99`|`98`|

</details>
<details open>

<summary>.step</summary>


|KeyPath|Old|New|
|-|-|-|
|`.step`|`1`|`2`|

</details>

</details>

## Step 3 to Step 4

<details open>

<summary>Variables</summary>

<details open>

<summary>.balances</summary>


|KeyPath|Old|New|
|-|-|-|
|`.balances(0)`|`102`|`103`|
|`.balances(1)`|`98`|`97`|

</details>
<details open>

<summary>.step</summary>


|KeyPath|Old|New|
|-|-|-|
|`.step`|`2`|`3`|

</details>

</details>

## Step 4 to Step 5

<details open>

<summary>Variables</summary>

<details open>

<summary>.action</summary>


|KeyPath|Old|New|
|-|-|-|
|`.action.value.amount`|`1`|`97`|

</details>
<details open>

<summary>.balances</summary>


|KeyPath|Old|New|
|-|-|-|
|`.balances(0)`|`103`|`200`|
|`.balances(1)`|`97`|`0`|

</details>
<details open>

<summary>.step</summary>


|KeyPath|Old|New|
|-|-|-|
|`.step`|`3`|`4`|

</details>

</details>

**Comment by rnbguy** [comment]
I added a commit to remove the leading dot and updated the example comments.

cc @andrey-kuprianov @tesnimab @hvanz

**Comment by andrey-kuprianov** [comment]
@rnbguy Let's wait till #254 is merged, because it's a long-awaiting already, and a large one. Afterwards, I believe, you'll need to merge `dev` into your branch, and adjust some `mdx` tests, because they will start failing (they count the number of generated trace files)

**Comment by rnbguy** [comment]
Yea, not a problem. But do you not count the `.itf.json` and `.tla` files only?

**Comment by hvanz** [comment]
Currently it counts all the files in the trace directory(ies), so this PR will break the tests.

**Comment by andrey-kuprianov** [comment]
#254 is merged, so please merge `dev` here and repair the tests (should be as easy as adjusting the file count)

**Comment by rnbguy** [comment]
Can we use `find $DIR -type f -iname "violation*.itf.json" -not -iname "violation.itf.json"` here to not consider other files?

https://github.com/informalsystems/modelator/blob/9fe58ff2929762b4de68ab71d46ad523e5aca48d/tests/cli/traces_num_generated.sh#L21

Works in mac and linux. I hope this fixes the mdx tests.

Btw, since these are tests, they should be on CI - atleast with manual trigger.

**Comment by andrey-kuprianov** [comment]
> Can we use find $DIR -iname "violation*.itf.json" -not -iname "violation.itf.json" here to not consider other files?

@rnbguy sure; please adjust the testing code/scripts as you find appropriate

**Review by andrey-kuprianov — APPROVED** [review]
Looks great, Rano! This is a substantial improvement for usability.

**Pull request merged**
